name: Daily Tefillah Update

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      force_send:
        description: "Force send now"
        required: false
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests convertdate pyluach

      - run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_SEND: ${{ github.event.inputs.force_send == 'true' && '1' || '0' }}
